name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: true
    
    - name: Docker Build and Push
      uses: docker/build-push-action@v2.6.1
      with:
        context: '.'
        push: true
        tags: 'ahmedwadod/hello-world-k8s:latest'
        labels: 'latest'
